import 'package:flutter/material.dart';

import 'playlist_models.dart';

const mockTempoPlaylists = [
  TempoPlaylist(
    id: 'night-tempo-walk',
    title: 'Night Tempo Walk',
    subtitle: 'Neon city loops for locked-in evening strides',
    imageAsset: 'assets/images/musicCover1.webp',
    bpm: 110,
    trackCount: 24,
    durationMinutes: 94,
    category: 'Walking',
    mood: 'Focused',
    isPinned: true,
    wasRecentlyPlayed: true,
    colors: [Color(0xFF17363A), Color(0xFF42E07C)],
  ),
  TempoPlaylist(
    id: 'steady-asphalt',
    title: 'Steady Asphalt',
    subtitle: 'Confident BPM pockets for repeatable run days',
    imageAsset: 'assets/images/musicCover2.webp',
    bpm: 116,
    trackCount: 31,
    durationMinutes: 112,
    category: 'Running',
    mood: 'Driven',
    wasRecentlyPlayed: true,
    colors: [Color(0xFF10232B), Color(0xFF6FE7F2)],
  ),
  TempoPlaylist(
    id: 'recovery-loop',
    title: 'Recovery Loop',
    subtitle: 'Soft reset energy for easy cooldown sessions',
    imageAsset: 'assets/images/musicCover3.webp',
    bpm: 98,
    trackCount: 18,
    durationMinutes: 67,
    category: 'Walking',
    mood: 'Calm',
    wasRecentlyPlayed: true,
    colors: [Color(0xFF24362B), Color(0xFF7AE38D)],
  ),
  TempoPlaylist(
    id: 'warm-street-start',
    title: 'Warm Street Start',
    subtitle: 'A gentle ramp before the pace starts clicking',
    imageAsset: 'assets/images/musicCover4.webp',
    bpm: 104,
    trackCount: 20,
    durationMinutes: 71,
    category: 'Walking',
    mood: 'Warm up',
    colors: [Color(0xFF332217), Color(0xFFFFC857)],
  ),
  TempoPlaylist(
    id: 'after-hours-tempo',
    title: 'After Hours Tempo',
    subtitle: 'Dark pulse and smooth momentum for late runs',
    imageAsset: 'assets/images/musicCover5.webp',
    bpm: 121,
    trackCount: 27,
    durationMinutes: 101,
    category: 'Running',
    mood: 'Dark',
    colors: [Color(0xFF261836), Color(0xFF6B8DFF)],
  ),
  TempoPlaylist(
    id: 'glass-mile',
    title: 'Glass Mile',
    subtitle: 'Polished synth edges for focused tempo work',
    imageAsset: 'assets/images/musicCover6.webp',
    bpm: 108,
    trackCount: 22,
    durationMinutes: 79,
    category: 'Running',
    mood: 'Focused',
    wasRecentlyPlayed: true,
    colors: [Color(0xFF17303B), Color(0xFF59D0E3)],
  ),
  TempoPlaylist(
    id: 'sunday-motion',
    title: 'Sunday Motion',
    subtitle: 'Easygoing picks for longer low-pressure walks',
    imageAsset: 'assets/images/musicCover7.webp',
    bpm: 96,
    trackCount: 16,
    durationMinutes: 58,
    category: 'Walking',
    mood: 'Calm',
    colors: [Color(0xFF243126), Color(0xFF8ACB88)],
  ),
];
